//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoValueManager.Models.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvoValueManager.Server.Models.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string ChallengeState_Cancelled {
            get {
                return ResourceManager.GetString("ChallengeState_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string ChallengeState_Completed {
            get {
                return ResourceManager.GetString("ChallengeState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string ChallengeState_InProgress {
            get {
                return ResourceManager.GetString("ChallengeState_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ChallengeState_New {
            get {
                return ResourceManager.GetString("ChallengeState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string ChallengeState_Suspended {
            get {
                return ResourceManager.GetString("ChallengeState_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bravery.
        /// </summary>
        public static string Value_Bravery {
            get {
                return ResourceManager.GetString("Value_Bravery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care.
        /// </summary>
        public static string Value_Care {
            get {
                return ResourceManager.GetString("Value_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth.
        /// </summary>
        public static string Value_Growth {
            get {
                return ResourceManager.GetString("Value_Growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        public static string Value_Presence {
            get {
                return ResourceManager.GetString("Value_Presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust.
        /// </summary>
        public static string Value_Trust {
            get {
                return ResourceManager.GetString("Value_Trust", resourceCulture);
            }
        }
    }
}
